/**
 * test_puppeteer.ts - Manual test for Puppeteer PDF generation and dynamic scraping
 * Run: npx tsx tests_manual/test_puppeteer.ts
 */

import { browserService } from '../src/backend/services/BrowserService.js';
import { WebPageContent } from '../src/backend/services/WebPageContent.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  console.log('=== Puppeteer Integration Manual Test ===\n');

  try {
    // 1. Test PDF generation
    console.log('Step 1: Generating PDF...');
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
          h1 { color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }
          p { font-size: 14px; line-height: 1.6; }
          .highlight { background-color: #f4f4f4; padding: 10px; border-left: 5px solid #ffcc00; }
        </style>
      </head>
      <body>
        <h1>Hello Norayr!</h1>
        <p>This PDF was generated by Puppeteer from a Node.js process.</p>
        <div class="highlight">
          <p><strong>Status:</strong> Success! The layout, margins, and CSS rendering work perfectly.</p>
        </div>
      </body>
      </html>
    `;

    const projectRoot = path.join(__dirname, '../');
    const pdfPath = path.join(projectRoot, 'workspace', 'test_puppeteer_output.pdf');

    await browserService.generatePdf(htmlContent, pdfPath);
    console.log(`PDF saved to: ${pdfPath}`);

    // 2. Test dynamic scraping
    console.log('\nStep 2: Scraping Wildberries...');
    const wildberriesUrl = 'https://www.wildberries.am/catalog/184991220/detail.aspx?size=304349044';
    const webPage = new WebPageContent();

    console.log(`Fetching ${wildberriesUrl} dynamically...`);
    const content = await webPage.fetchPage({ url: wildberriesUrl, dynamic: true });

    // Also get the raw HTML directly from browserService for debugging
    const rawHtml = await browserService.fetchDynamicPage(wildberriesUrl);
    const fs = await import('fs/promises');
    await fs.writeFile(path.join(projectRoot, 'workspace', 'wb.html'), rawHtml);
    console.log(`Raw HTML saved to workspace/wb.html for debugging.`);

    console.log('Scraped Content Preview (first 1000 characters):');
    console.log('--------------------------------------------------');
    console.log(content.substring(0, 1000));
    console.log('--------------------------------------------------');
    console.log('Content length:', content.length);

    if (content.length > 500 && !content.includes('Error')) {
      console.log('\nSUCCESS: Puppeteer integration manual test passed!');
    } else {
      console.log('\nFAILURE: Scraped content seems too short or contains error.');
    }

  } catch (error) {
    console.error('Test run encountered an error:', error);
  } finally {
    // Close the browser instance to clean up processes
    await browserService.close();
  }
}

main();
